### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by Mingus85** [jsboulanger/feedback#5]
Hi, I'm a noob running Ruby 2.3 on Rails 4 and Ubuntu 14. When I follow the install directions from the readme I get the following error. What am I doing wrong?

```
$ rails generate feedback_form --skip-jquery
[WARNING] Could not load generator "generators/feedback_form_generator". Error: uninitialized constant Rails::Generator.
/home/ubuntu/workspace/lib/generators/lib/insert_routes.rb:3:in `<top (required)>'
/home/ubuntu/workspace/lib/generators/feedback_form_generator.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/generators.rb:332:in `block (2 levels) in lookup'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/generators.rb:328:in `each'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/generators.rb:328:in `block in lookup'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/generators.rb:327:in `each'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/generators.rb:327:in `lookup'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/generators.rb:138:in `find_by_namespace'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/generators.rb:155:in `invoke'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/commands/generate.rb:13:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:50:in `generate'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Could not find generator 'feedback_form'. Maybe you meant 'generator', 'erb:scaffold' or 'resource_route'
Run `rails generate --help` for more options.
```

**Comment by jsboulanger** [comment]
This library is rather old, I have not tested it on Rails 4, but you can try the Rails 3.x installation instructions in the README.
